[package]
name = "orx-concurrent-ordered-bag"
version = "2.11.0"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "An efficient, convenient and lightweight grow-only concurrent data structure allowing high performance and ordered concurrent collection."
license = "MIT OR Apache-2.0"
repository = "https://github.com/orxfun/orx-ordered-concurrent-bag/"
keywords = [
    "concurrency",
    "parallelization",
    "data-structures",
    "atomic",
    "lock-free",
]
categories = ["data-structures", "concurrency", "rust-patterns", "no-std"]

[dependencies]
orx-pseudo-default = { version = "2.0.0", default-features = false }
orx-pinned-vec = "3.15"
orx-fixed-vec = "3.15"
orx-split-vec = "3.15"
orx-pinned-concurrent-col = "2.12"

[dev-dependencies]
orx-concurrent-iter = "1.30.0"
orx-iterable = "1.2.0"
test-case = "3.3.1"
