[package]
name = "orx-concurrent-ordered-bag"
version = "1.3.0"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "An efficient, convenient and lightweight grow-only concurrent data structure allowing high performance and ordered concurrent collection."
license = "MIT"
repository = "https://github.com/orxfun/orx-ordered-concurrent-bag/"
keywords = [
    "concurrency",
    "parallelization",
    "data-structures",
    "atomic",
    "lock-free",
]
categories = ["data-structures", "concurrency", "rust-patterns"]

[dependencies]
orx-fixed-vec = "2.12"
orx-pinned-concurrent-col = "1.5"
orx-pinned-vec = "2.12"
orx-split-vec = "2.14"

[dev-dependencies]
orx-concurrent-iter = "1.10"
test-case = "3.3.1"
